### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sandeshfromindia** [seiyria/posys#105]
hey facing some issue while installing on windows 10,
i hvae node --version v6.9.1
npm --version 4.0.3

I followed normal installation steps:
clone the repository
install postgresql
npm install -g ionic
npm install
create src/server/server.config.json (sample below)
npm run migrate:latest (set up the database)
npm run seed:run (get some sample data in the db to work with)
npm start:server (in one terminal)
npm start (in another terminal)

but getting follwing warnings :

D:\node\posys>npm install --msvs_version=2017
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.2.1 requires a peer of zone.js@^0.6.21 but none was installed.
npm WARN @angular/http@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN tslint@5.2.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of @angular/compiler@~2.1.1 but none was installed.
npm WARN codelyzer@1.0.0-beta.3 requires a peer of @angular/core@~2.1.1 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/common@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler-cli@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/core@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/forms@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/http@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser-dynamic@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-server@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of rxjs@5.0.1 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of zone.js@0.7.2 but none was installed.
npm WARN tslint-eslint-rules@4.1.1 requires a peer of tslint@^5.0.0 but none was installed.

and then i executed 
=> npm run migrate:latest

got follwing error

> posys@0.0.1 migrate:latest D:\node\posys
> knex migrate:latest --knexfile src/server/knexfile.ts

Requiring external module ts-node/register
Working directory changed to D:\node\posys\src\server
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sandesh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "migrate:latest"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! posys@0.0.1 migrate:latest: `knex migrate:latest --knexfile src/server/knexfile.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posys@0.0.1 migrate:latest script 'knex migrate:latest --knexfile src/server/knexfile.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the posys package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest --knexfile src/server/knexfile.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs posys
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls posys
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node\posys\npm-debug.log

even tried executing
=> npm start
got error like follows

.
.
.
.
22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 157 
            Cannot find name 'T'.

     L156:  mapValues<T extends object, TKey extends keyof T>(
     L157:      this: LoDashExplicitWrapper<T | null | undefined>,
     L158:      iteratee: string

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 157 
            The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

     L156:  mapValues<T extends object, TKey extends keyof T>(
     L157:      this: LoDashExplicitWrapper<T | null | undefined>,
     L158:      iteratee: string

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 158 
            Cannot find name 'iteratee'.

     L157:      this: LoDashExplicitWrapper<T | null | undefined>,
     L158:      iteratee: string
     L159:  ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 158 
            Cannot find name 'string'.

     L157:      this: LoDashExplicitWrapper<T | null | undefined>,
     L158:      iteratee: string
     L159:  ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            Cannot find name 'LoDashExplicitWrapper'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            Cannot find name 'P'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            Cannot find name 'keyof'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            Cannot find name 'T'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 159 
            Cannot find name 'any'.

     L158:              iteratee: string
     L159:          ): LoDashExplicitWrapper<{ [P in keyof T]: any }>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 164 
            Cannot find name 'mapValues'.

     L164:  mapValues<TResult>(
     L165:      this: LoDashExplicitWrapper<string | null | undefined>,

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 165 
            Cannot find name 'LoDashExplicitWrapper'.

     L164:  mapValues<TResult>(
     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 165 
            The '|' operator is not allowed for boolean types. Consider using '||' instead.

     L164:  mapValues<TResult>(
     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 165 
            Cannot find name 'string'.

     L164:  mapValues<TResult>(
     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 165 
            The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

     L164:  mapValues<TResult>(
     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 166 
            Cannot find name 'callback'.

     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>
     L167:  ): LoDashExplicitWrapper<NumericDictionary<TResult>>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 166 
            Cannot find name 'StringIterator'.

     L165:      this: LoDashExplicitWrapper<string | null | undefined>,
     L166:      callback: StringIterator<TResult>
     L167:  ): LoDashExplicitWrapper<NumericDictionary<TResult>>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 167 
            Cannot find name 'LoDashExplicitWrapper'.

     L166:              callback: StringIterator<TResult>
     L167:          ): LoDashExplicitWrapper<NumericDictionary<TResult>>;

[22:12:02]  typescript: ... D:/node/posys/node_modules/@types/lodash/object/mapValues.d.ts, line: 172 
            Cannot find name 'mapValues'.

     L172:          mapValues<T>(this: LoDashExplicitWrapper<Dictionary<T> | null | undefined>): LoDashExplicitWrapper<D
.
.
.
.
.

**Comment by seiyria** [comment]
Unfortunately I have no idea and this application is not maintained as I didn't find a suitable market for it. Sorry.
